[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vote = "FZNg89Lo9GbtH2A1NNFASS5M4iSKYxkSHxNZwk8MWqJZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/izomana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
