[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vote_program = "6RwMBpB1DMT3D663HJNZpUmKTquGVi9MVvKN1Dt8DyD8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/izomana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
