[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vote_two = "ELYN9fcwdLFDehJnq1SWN9CRJgrishc31wwKB3SsE6jV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/izomana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
