[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault_two = "6Cw8Ums2GFDMtwRaEfCzCw9BPohrRH4YEahk1UVocQHz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/izomana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
