[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solgig = "9WFWMjBDF32pGEEjP6XHaGUkuQXqcgx1eFjRqLSh2dbA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/izomana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
