[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
solgig = "A4wtrzSWg1PTHiM1NPveZSmP7vDX3gUgHstwcdGd2w8F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/izomana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
